// <auto-generated />
using System;
using DrakionTech.Crm.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrakionTech.Crm.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311164732_CambiarEmailACorreo")]
    partial class CambiarEmailACorreo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactoId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoActividadId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalCalendarEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoActividadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioInternoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EstadoActividadId");

                    b.HasIndex("Inicio");

                    b.HasIndex("OportunidadId");

                    b.HasIndex("TipoActividadId");

                    b.HasIndex("UsuarioInternoId");

                    b.HasIndex("UsuarioInternoId", "Inicio", "Fin");

                    b.ToTable("Actividades", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.ActividadUsuario", b =>
                {
                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioInternoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsResponsable")
                        .HasColumnType("bit");

                    b.HasKey("ActividadId", "UsuarioInternoId");

                    b.HasIndex("UsuarioInternoId");

                    b.ToTable("ActividadUsuarios", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Ciudades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Bogotá",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Medellín",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Nueva York",
                            PaisId = 2
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEspecial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVinculacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RolContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("RolContactoId");

                    b.ToTable("Contactos", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoOtro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEspecial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HaTrabajadoAntes")
                        .HasColumnType("bit");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("RepresentanteLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("SectorOtro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.HasIndex("PaisId");

                    b.HasIndex("SectorId");

                    b.ToTable("Empresas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Empresas_Estado", "(\r\n                        (EstadoId IS NOT NULL AND EstadoOtro IS NULL)\r\n                        OR\r\n                        (EstadoId IS NULL AND LTRIM(RTRIM(EstadoOtro)) <> '')\r\n                    )");

                            t.HasCheckConstraint("CK_Empresas_Sector", "(\r\n                        (SectorId IS NOT NULL AND SectorOtro IS NULL)\r\n                        OR\r\n                        (SectorId IS NULL AND LTRIM(RTRIM(SectorOtro)) <> '')\r\n                    )");
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Estados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Lead"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Prospecto"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cliente"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Inactivo"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.EstadoActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("EstadoActividad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Programada"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Completada"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.HistorialCambioOportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtapaAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EtapaNueva")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OportunidadId");

                    b.ToTable("HistorialCambiosOportunidad", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Oportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactoPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Etapa")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEstimadaCierre")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContactoPrincipalId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Oportunidades", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoIso = "CO",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = 2,
                            CodigoIso = "EEUU",
                            Nombre = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.PrefijoTelefonico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("PrefijosTelefonicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "+57",
                            Nombre = "Colombia",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "+1",
                            Nombre = "Estados Unidos",
                            PaisId = 2
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Propuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamanoArchivo")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OportunidadId");

                    b.ToTable("Propuestas", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.RolContacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RolesContacto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Desconocido"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CEO"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "CTO"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "CFO"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "COO"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Director"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Gerente"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Project Manager"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Líder Técnico"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Compras"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Ventas"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Marketing"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Sectores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Salud"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Educación"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Retail Comercio"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Logística y Transporte"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Inmobiliario"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Finanzas"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Manufactura"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Servicios Profesionales"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Gobierno / Sector Público"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Construcción"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Turismo y Hospitalidad"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Agricultura / Agroindustria"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Energía"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Tecnología"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.TipoActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("TipoActividad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Llamada telefónica con el cliente",
                            Nombre = "Llamada"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Reunión presencial o virtual",
                            Nombre = "Reunión"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Envío o seguimiento vía correo electrónico",
                            Nombre = "Correo"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Seguimiento comercial",
                            Nombre = "Seguimiento"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Demostración de producto o servicio",
                            Nombre = "Demo"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.UsuarioInterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Email");

                    b.ToTable("UsuarioInterno", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Actividad", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrakionTech.Crm.Data.Entities.Empresa", "Empresa")
                        .WithMany("Actividades")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrakionTech.Crm.Data.Entities.EstadoActividad", "EstadoActividad")
                        .WithMany("Actividades")
                        .HasForeignKey("EstadoActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.Oportunidad", "Oportunidad")
                        .WithMany()
                        .HasForeignKey("OportunidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrakionTech.Crm.Data.Entities.TipoActividad", "TipoActividad")
                        .WithMany("Actividades")
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.UsuarioInterno", "UsuarioInterno")
                        .WithMany("ActividadesResponsable")
                        .HasForeignKey("UsuarioInternoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contacto");

                    b.Navigation("Empresa");

                    b.Navigation("EstadoActividad");

                    b.Navigation("Oportunidad");

                    b.Navigation("TipoActividad");

                    b.Navigation("UsuarioInterno");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.ActividadUsuario", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Actividad", "Actividad")
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.UsuarioInterno", "UsuarioInterno")
                        .WithMany("ActividadesAsignadas")
                        .HasForeignKey("UsuarioInternoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("UsuarioInterno");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Ciudad", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Contacto", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Empresa", "Empresa")
                        .WithMany("Contactos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.RolContacto", "RolContacto")
                        .WithMany()
                        .HasForeignKey("RolContactoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("RolContacto");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Empresa", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrakionTech.Crm.Data.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ciudad");

                    b.Navigation("Estado");

                    b.Navigation("Pais");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.HistorialCambioOportunidad", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Oportunidad", "Oportunidad")
                        .WithMany("HistorialCambios")
                        .HasForeignKey("OportunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oportunidad");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Oportunidad", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Contacto", "ContactoPrincipal")
                        .WithMany()
                        .HasForeignKey("ContactoPrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DrakionTech.Crm.Data.Entities.Empresa", "Empresa")
                        .WithMany("Oportunidades")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactoPrincipal");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.PrefijoTelefonico", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Pais", "Pais")
                        .WithMany("PrefijosTelefonicos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Propuesta", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Oportunidad", "Oportunidad")
                        .WithMany("Propuestas")
                        .HasForeignKey("OportunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oportunidad");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Actividad", b =>
                {
                    b.Navigation("UsuariosAsignados");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Empresa", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Contactos");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.EstadoActividad", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Oportunidad", b =>
                {
                    b.Navigation("HistorialCambios");

                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Pais", b =>
                {
                    b.Navigation("Ciudades");

                    b.Navigation("PrefijosTelefonicos");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.TipoActividad", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.UsuarioInterno", b =>
                {
                    b.Navigation("ActividadesAsignadas");

                    b.Navigation("ActividadesResponsable");
                });
#pragma warning restore 612, 618
        }
    }
}
