// <auto-generated />
using System;
using DrakionTech.Crm.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrakionTech.Crm.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327183129_normal")]
    partial class normal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactoId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoActividadId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalCalendarEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoActividadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioInternoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EstadoActividadId");

                    b.HasIndex("Inicio");

                    b.HasIndex("OportunidadId");

                    b.HasIndex("TipoActividadId");

                    b.HasIndex("UsuarioInternoId");

                    b.HasIndex("UsuarioInternoId", "Inicio", "Fin");

                    b.ToTable("Actividades", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.ActividadUsuario", b =>
                {
                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioInternoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsResponsable")
                        .HasColumnType("bit");

                    b.HasKey("ActividadId", "UsuarioInternoId");

                    b.HasIndex("UsuarioInternoId");

                    b.ToTable("ActividadUsuarios", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Ciudades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Bogotá",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Medellín",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cali",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Barranquilla",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Cartagena",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Bucaramanga",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Cúcuta",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Pereira",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Manizales",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Armenia",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Ibagué",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Neiva",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Villavicencio",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Pasto",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Popayán",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Santa Marta",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Valledupar",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Montería",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Sincelejo",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Riohacha",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Yopal",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Tunja",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Florencia",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Mocoa",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "San José del Guaviare",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Leticia",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Mitú",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Puerto Carreño",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Quibdó",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Arauca",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "San Andrés",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Inírida",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Buenaventura",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 34,
                            Nombre = "Buenos Aires",
                            PaisId = 2
                        },
                        new
                        {
                            Id = 35,
                            Nombre = "Córdoba",
                            PaisId = 2
                        },
                        new
                        {
                            Id = 36,
                            Nombre = "São Paulo",
                            PaisId = 4
                        },
                        new
                        {
                            Id = 37,
                            Nombre = "Rio de Janeiro",
                            PaisId = 4
                        },
                        new
                        {
                            Id = 38,
                            Nombre = "Santiago",
                            PaisId = 5
                        },
                        new
                        {
                            Id = 39,
                            Nombre = "Lima",
                            PaisId = 9
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Ciudad de México",
                            PaisId = 13
                        },
                        new
                        {
                            Id = 41,
                            Nombre = "Monterrey",
                            PaisId = 13
                        },
                        new
                        {
                            Id = 42,
                            Nombre = "New York",
                            PaisId = 14
                        },
                        new
                        {
                            Id = 43,
                            Nombre = "Los Ángeles",
                            PaisId = 14
                        },
                        new
                        {
                            Id = 46,
                            Nombre = "La Paz",
                            PaisId = 3
                        },
                        new
                        {
                            Id = 47,
                            Nombre = "Quito",
                            PaisId = 6
                        },
                        new
                        {
                            Id = 48,
                            Nombre = "Georgetown",
                            PaisId = 7
                        },
                        new
                        {
                            Id = 49,
                            Nombre = "Asunción",
                            PaisId = 8
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Paramaribo",
                            PaisId = 10
                        },
                        new
                        {
                            Id = 51,
                            Nombre = "Montevideo",
                            PaisId = 11
                        },
                        new
                        {
                            Id = 52,
                            Nombre = "Caracas",
                            PaisId = 12
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEspecial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVinculacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RolContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("RolContactoId");

                    b.ToTable("Contactos", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoOtro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEspecial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HaTrabajadoAntes")
                        .HasColumnType("bit");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("RepresentanteLegal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("SectorOtro")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.HasIndex("PaisId");

                    b.HasIndex("SectorId");

                    b.ToTable("Empresas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Empresas_Estado", "(\r\n                        (EstadoId IS NOT NULL AND EstadoOtro IS NULL)\r\n                        OR\r\n                        (EstadoId IS NULL AND LTRIM(RTRIM(EstadoOtro)) <> '')\r\n                    )");

                            t.HasCheckConstraint("CK_Empresas_Sector", "(\r\n                        (SectorId IS NOT NULL AND SectorOtro IS NULL)\r\n                        OR\r\n                        (SectorId IS NULL AND LTRIM(RTRIM(SectorOtro)) <> '')\r\n                    )");
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Estados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Lead"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Prospecto"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cliente"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Inactivo"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.EstadoActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("EstadoActividad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Programada"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Completada"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.GoogleEventoArchivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoogleEventoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleEventoId");

                    b.ToTable("GoogleEventoArchivos");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.HistorialCambioOportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtapaAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EtapaNueva")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OportunidadId");

                    b.ToTable("HistorialCambiosOportunidad", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Oportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactoPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Etapa")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEstimadaCierre")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContactoPrincipalId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Oportunidades", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoIso = "CO",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = 2,
                            CodigoIso = "AR",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 3,
                            CodigoIso = "BO",
                            Nombre = "Bolivia"
                        },
                        new
                        {
                            Id = 4,
                            CodigoIso = "BR",
                            Nombre = "Brasil"
                        },
                        new
                        {
                            Id = 5,
                            CodigoIso = "CL",
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = 6,
                            CodigoIso = "EC",
                            Nombre = "Ecuador"
                        },
                        new
                        {
                            Id = 7,
                            CodigoIso = "GY",
                            Nombre = "Guyana"
                        },
                        new
                        {
                            Id = 8,
                            CodigoIso = "PY",
                            Nombre = "Paraguay"
                        },
                        new
                        {
                            Id = 9,
                            CodigoIso = "PE",
                            Nombre = "Perú"
                        },
                        new
                        {
                            Id = 10,
                            CodigoIso = "SR",
                            Nombre = "Surinam"
                        },
                        new
                        {
                            Id = 11,
                            CodigoIso = "UY",
                            Nombre = "Uruguay"
                        },
                        new
                        {
                            Id = 12,
                            CodigoIso = "VE",
                            Nombre = "Venezuela"
                        },
                        new
                        {
                            Id = 13,
                            CodigoIso = "MX",
                            Nombre = "México"
                        },
                        new
                        {
                            Id = 14,
                            CodigoIso = "US",
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            Id = 15,
                            CodigoIso = "CA",
                            Nombre = "Canadá"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.PrefijoTelefonico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("PrefijosTelefonicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "+57",
                            Nombre = "Colombia",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "+1",
                            Nombre = "Estados Unidos",
                            PaisId = 14
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "+54",
                            Nombre = "Argentina",
                            PaisId = 2
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "+591",
                            Nombre = "Bolivia",
                            PaisId = 3
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "+55",
                            Nombre = "Brasil",
                            PaisId = 4
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "+56",
                            Nombre = "Chile",
                            PaisId = 5
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "+593",
                            Nombre = "Ecuador",
                            PaisId = 6
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "+592",
                            Nombre = "Guyana",
                            PaisId = 7
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "+595",
                            Nombre = "Paraguay",
                            PaisId = 8
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "+51",
                            Nombre = "Perú",
                            PaisId = 9
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "+597",
                            Nombre = "Surinam",
                            PaisId = 10
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "+598",
                            Nombre = "Uruguay",
                            PaisId = 11
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "+58",
                            Nombre = "Venezuela",
                            PaisId = 12
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "+52",
                            Nombre = "México",
                            PaisId = 13
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "+1",
                            Nombre = "Canadá",
                            PaisId = 15
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Propuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamanoArchivo")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OportunidadId");

                    b.ToTable("Propuestas", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.RolContacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RolesContacto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Desconocido"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CEO"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "CTO"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "CFO"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "COO"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Director"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Gerente"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Project Manager"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Líder Técnico"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Compras"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Ventas"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Marketing"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Sectores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Salud"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Educación"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Retail Comercio"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Logística y Transporte"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Inmobiliario"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Finanzas"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Manufactura"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Servicios Profesionales"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Gobierno / Sector Público"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Construcción"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Turismo y Hospitalidad"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Agricultura / Agroindustria"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Energía"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Tecnología"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.TipoActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("TipoActividad", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Llamada telefónica con el cliente",
                            Nombre = "Llamada"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Reunión presencial o virtual",
                            Nombre = "Reunión"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Envío o seguimiento vía correo electrónico",
                            Nombre = "Correo"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Seguimiento comercial",
                            Nombre = "Seguimiento"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Demostración de producto o servicio",
                            Nombre = "Demo"
                        });
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.UsuarioInterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Email");

                    b.ToTable("UsuarioInterno", (string)null);
                });

            modelBuilder.Entity("GoogleEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleEventId")
                        .IsUnique()
                        .HasFilter("[GoogleEventId] IS NOT NULL");

                    b.ToTable("GoogleEventos", (string)null);
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Actividad", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrakionTech.Crm.Data.Entities.Empresa", "Empresa")
                        .WithMany("Actividades")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrakionTech.Crm.Data.Entities.EstadoActividad", "EstadoActividad")
                        .WithMany("Actividades")
                        .HasForeignKey("EstadoActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.Oportunidad", "Oportunidad")
                        .WithMany()
                        .HasForeignKey("OportunidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrakionTech.Crm.Data.Entities.TipoActividad", "TipoActividad")
                        .WithMany("Actividades")
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.UsuarioInterno", "UsuarioInterno")
                        .WithMany("ActividadesResponsable")
                        .HasForeignKey("UsuarioInternoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contacto");

                    b.Navigation("Empresa");

                    b.Navigation("EstadoActividad");

                    b.Navigation("Oportunidad");

                    b.Navigation("TipoActividad");

                    b.Navigation("UsuarioInterno");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.ActividadUsuario", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Actividad", "Actividad")
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.UsuarioInterno", "UsuarioInterno")
                        .WithMany("ActividadesAsignadas")
                        .HasForeignKey("UsuarioInternoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("UsuarioInterno");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Ciudad", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Contacto", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Empresa", "Empresa")
                        .WithMany("Contactos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.RolContacto", "RolContacto")
                        .WithMany()
                        .HasForeignKey("RolContactoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("RolContacto");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Empresa", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DrakionTech.Crm.Data.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DrakionTech.Crm.Data.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ciudad");

                    b.Navigation("Estado");

                    b.Navigation("Pais");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.GoogleEventoArchivo", b =>
                {
                    b.HasOne("GoogleEvento", "GoogleEvento")
                        .WithMany("Archivos")
                        .HasForeignKey("GoogleEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoogleEvento");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.HistorialCambioOportunidad", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Oportunidad", "Oportunidad")
                        .WithMany("HistorialCambios")
                        .HasForeignKey("OportunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oportunidad");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Oportunidad", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Contacto", "ContactoPrincipal")
                        .WithMany()
                        .HasForeignKey("ContactoPrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DrakionTech.Crm.Data.Entities.Empresa", "Empresa")
                        .WithMany("Oportunidades")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactoPrincipal");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.PrefijoTelefonico", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Pais", "Pais")
                        .WithMany("PrefijosTelefonicos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Propuesta", b =>
                {
                    b.HasOne("DrakionTech.Crm.Data.Entities.Oportunidad", "Oportunidad")
                        .WithMany("Propuestas")
                        .HasForeignKey("OportunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oportunidad");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Actividad", b =>
                {
                    b.Navigation("UsuariosAsignados");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Empresa", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Contactos");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.EstadoActividad", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Oportunidad", b =>
                {
                    b.Navigation("HistorialCambios");

                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.Pais", b =>
                {
                    b.Navigation("Ciudades");

                    b.Navigation("PrefijosTelefonicos");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.TipoActividad", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("DrakionTech.Crm.Data.Entities.UsuarioInterno", b =>
                {
                    b.Navigation("ActividadesAsignadas");

                    b.Navigation("ActividadesResponsable");
                });

            modelBuilder.Entity("GoogleEvento", b =>
                {
                    b.Navigation("Archivos");
                });
#pragma warning restore 612, 618
        }
    }
}
